### ISSUE TITLE
Template option not working with Translation Field

### ISSUE THREAD

**Issue by u12206050** [codihaus/directus-extension-hierarchy-layout#1]
Hey, great addition to Directus!

The layout template option doesn't seem to work with Translation fields. It seems like it isn't fetching the data from the translation relation. 
As you can see on the image below, it is supposed to fetch `translations.*` or the specified fields as defined on the the schema for that field eg. `translations.title, translations.lang` which the translations display needs.

<img width="186" alt="Screenshot 2024-07-25 at 12 21 44" src="https://github.com/user-attachments/assets/48f76c17-1dfd-4800-b82a-5fc096c77679">

**Comment by codihaus** [comment]
The title is displayed using Directus's display feature, so if your interface is set up correctly, it should display fully. Could you provide screenshots of the two setup fields you are currently selecting?
@u12206050 

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/a6040544-d111-453c-9119-ea9cd2fd1436">

**Comment by u12206050** [comment]
I select the actual translation field not a field on the translation item (such as you did with title)
The display setting of the translation field is set to Translations (preview translations)

Can attach images once I'm back at work.

**Comment by u12206050** [comment]
Layout setup:
<img width="292" alt="Screenshot 2024-07-26 at 22 19 13" src="https://github.com/user-attachments/assets/a8fbd0d5-0e9c-482a-94ed-f793859e0f94">

The interface display setup:
<img width="857" alt="Screenshot 2024-07-26 at 22 19 36" src="https://github.com/user-attachments/assets/30fb67fe-a411-46c7-95c8-82f28e786f78">

**Comment by u12206050** [comment]
There is a utility function in Directus that gets all the fields for a given template string called `adjustFieldsForDisplays`

**Comment by u12206050** [comment]
I do see it works as expected when I select `translations.title` then it does actually display as a string. Thanks, just a bit weird that it doesn't work the same as the other layouts in that regard like cards.
